export const fullContent = `<h1>Welcome to SHEditor</h1><p>SHEditor is a modern <strong>framework-agnostic</strong> WYSIWYG HTML editor built with <em>TypeScript</em>.</p><p>Try <span style="color: #6750f2">text color</span>, <mark style="background-color: #fff2a8">highlight</mark>, H<sub>2</sub>O, x<sup>2</sup>, alignment, or your own ideas directly in the browser.</p><h2>A clean editing foundation</h2><ul><li>Semantic HTML and stable JSON output</li><li>React, Vue, Angular, and Vanilla JavaScript</li><li>Accessible controls with first-class RTL support</li></ul><blockquote>Great editing tools should stay out of the writer’s way.</blockquote><p>Explore the <a href="https://github.com/mahdiporkar/SHEditor">open-source project</a> on GitHub.</p>`;

export const rtlContent = `<h1>ویرایشگر حرفه‌ای SHEditor</h1><p>این یک نمونهٔ واقعی برای بررسی و ویرایش متن فارسی و راست‌به‌چپ است.</p><p>در این محیط می‌توانید متن فارسی و <strong>English</strong> را به‌صورت ترکیبی بنویسید و قالب‌بندی کنید.</p><h2>پشتیبانی واقعی از RTL</h2><ul><li>تیتر و پاراگراف فارسی</li><li>فهرست‌های راست‌به‌چپ</li><li>خروجی HTML تمیز و امن</li></ul><blockquote>نسخه SHEditor 0.1 برای React، Vue و Angular طراحی شده است.</blockquote>`;

export const extensionContent = `<h1>Custom extension</h1><p>The playground registers a real ProseMirror plugin through SHEditor’s public <code>defineExtension</code> API.</p><blockquote>💡 This blockquote receives a callout treatment from plugin decorations—without changing SHEditor core.</blockquote><p>Edit the callout or undo your changes. It remains part of the real document model.</p>`;

export const readonlyContent = `<h1>One document, two modes</h1><p>This content uses the same SHEditor schema and rendering in editable and readonly states.</p><blockquote>Toggle editing without recreating the editor.</blockquote><p>The command calls the real <code>editor.setEditable()</code> API.</p>`;
export const imageContent = `<h1>Three ways to add images</h1><p>Use the image button for a URL, embedded Base64 file, or the configured upload adapter. You can also drop or paste an image. Select an image and drag a corner handle to resize it.</p>`;
export const tableContent = `<h1>Professional tables</h1><p>Click inside a cell to use the row, column, merge, split, header, and delete controls. Drag column boundaries to resize.</p><table><tbody><tr><th><p>Feature</p></th><th><p>Status</p></th><th><p>Owner</p></th></tr><tr><td><p>Image upload</p></td><td><p>Ready</p></td><td><p>Media</p></td></tr><tr><td><p>Tables</p></td><td><p>Ready</p></td><td><p>Editor</p></td></tr></tbody></table><p></p>`;

export const snippets = {
  react: `import { useState } from 'react';\nimport { SHEditor } from '@sheditor/react';\n\nexport function ArticleEditor() {\n  const [content, setContent] = useState('<p>Hello SHEditor</p>');\n  return <SHEditor value={content} onChange={setContent} />;\n}`,
  vue: `<script setup lang="ts">\nimport { ref } from 'vue';\nimport { SHEditor } from '@sheditor/vue';\nconst content = ref('<p>Hello SHEditor</p>');\n</script>\n\n<template>\n  <SHEditor v-model="content" />\n</template>`,
  angular: `import { FormControl, ReactiveFormsModule } from '@angular/forms';\nimport { SHEditorComponent } from '@sheditor/angular';\n\n@Component({\n  imports: [ReactiveFormsModule, SHEditorComponent],\n  template: '<she-editor [formControl]="content" />'\n})\nexport class ArticleEditor {\n  content = new FormControl('<p>Hello SHEditor</p>');\n}`,
  vanilla: `import { createEditor } from '@sheditor/core';\n\nconst editor = createEditor({\n  element: document.querySelector('#editor'),\n  content: '<p>Hello SHEditor</p>',\n  onUpdate: ({ editor }) => console.log(editor.getHTML()),\n});`,
  extension: `import { defineExtension } from '@sheditor/core';\nimport { Plugin } from 'prosemirror-state';\nimport { Decoration, DecorationSet } from 'prosemirror-view';\n\nexport const calloutExtension = defineExtension({\n  name: 'demoCallout',\n  plugins: () => [new Plugin({\n    props: { decorations(state) {\n      const items = [];\n      state.doc.descendants((node, pos) => {\n        if (node.type.name === 'blockquote')\n          items.push(Decoration.node(pos, pos + node.nodeSize, { class: 'demo-callout' }));\n      });\n      return DecorationSet.create(state.doc, items);\n    } },\n  })],\n});`,
} as const;
